In [1]:
import numpy as np
import pandas as pd

In [2]:
# wczytujemy nasz przykładowy zbiór danych jako ramkę danych

df = pd.read_csv('https://raw.githubusercontent.com/mateuszr/ml-course-1/main/datasets/dummy.csv')

In [3]:
# oto jak wygląda w całości

df

# zwrócmy uwagę, że NaN pojawia się także w kolumnie gdzie mamy wartości tekstowe

     A    B    C  D      E
0  1.0  2.0  3.0  4  First
1  NaN  5.0  6.0  3    NaN
2  1.0  NaN  NaN  2    NaN
3  7.0  3.0  NaN  1  First
4  1.0  3.0  2.0  2  Third
5  7.0  4.0  2.0  4  Forth

In [4]:
# możemy użyc funkcji "describe()" na takiej ramce danych aby poznać podstawowe
# statystyki o wartościach liczbowych. Rezultatem działania funkcji "describe()"
# jest również ramka danych.
# Statystyki podane są wg kolumn, dla poszczególnych kolumn z osobna.
# Na uwagę zasługuje pierwszy wiersz "count", zliczający ile w danej kolumnie
# jest wartości niepustych (tj wartości które nie są NA/NaN/NULL)

df.describe()

              A         B         C         D
count  5.000000  5.000000  4.000000  6.000000
mean   3.400000  3.400000  3.250000  2.666667
std    3.286335  1.140175  1.892969  1.211060
min    1.000000  2.000000  2.000000  1.000000
25%    1.000000  3.000000  2.000000  2.000000
50%    1.000000  3.000000  2.500000  2.500000
75%    7.000000  4.000000  3.750000  3.750000
max    7.000000  5.000000  6.000000  4.000000

In [5]:
# skoro jest to ramka danych, możemy wyświetlić tylko interesujący nas wiersz "count"

df.describe().loc["count"]

A    5.0
B    5.0
C    4.0
D    6.0
Name: count, dtype: float64

In [6]:
# inną metodą na wyświetlenie brakujących wartości jest funkcja "isna()"
# w tym wypadku funkcja zwróci wartość True tam, gdzie brakuje wartości.

df.isna()

       A      B      C      D      E
0  False  False  False  False  False
1   True  False  False  False   True
2  False   True   True  False   True
3  False  False   True  False  False
4  False  False  False  False  False
5  False  False  False  False  False

In [7]:
# taki wynik możemy zliczyć aby poznać statystyki brakujących danych.
# w tym wypadku zliczmay wszytskie brakujące dane wg kolumn
# przy pomocy funkcji agregującej "sum()"

df.isna().sum()

A    1
B    1
C    2
D    0
E    2
dtype: int64

In [8]:
# Funkcja "sum()" domyślnie zliczy wartości "True" wg. kolumn,
# ale podając parametr "axis = 1" funckja policzy te wartości
# wg. wierszy.

df.isna().sum(axis = 1)

0    0
1    2
2    3
3    1
4    0
5    0
dtype: int64

In [9]:
# Czasami nie musimy zliczać brakujących wartości, tylko chcemy poznać
# kolumny/wiersze gdzie one występują (np. aby poźniej takie wiersze usunąć).
# Można użyc funkcji "any()", która zwróci wartość "True" tam, gdzie kolumna
# zawiera brakujące wartości.

df.isna().any()

A     True
B     True
C     True
D    False
E     True
dtype: bool

In [10]:
# ...i to samo co poprzednio, ale wg wierszy:

df.isna().any(axis = 1)

0    False
1     True
2     True
3     True
4    False
5    False
dtype: bool

In [11]:
# Czasami chcemy przejrzeć tylko te wiersze, gdzie brakuje danych:
# Możemy użyc poprzedniego wyrażenia jako "filtra", który
# zaznaczy tylko te wiersze ramki danych, które posiadają brakujące dane
# (wyswietli te wiersze gdzie jest wartość "True")

df[df.isna().any(axis = 1)]

     A    B    C  D      E
1  NaN  5.0  6.0  3    NaN
2  1.0  NaN  NaN  2    NaN
3  7.0  3.0  NaN  1  First

In [12]:
# Moglibyśmy użyc podobnej konstrukcji, aby wybrać tylko "pełne" wiersze,
# tj. te, w których nie ma brakujących danych:

df[~ df.isna().any(axis = 1)]

     A    B    C  D      E
0  1.0  2.0  3.0  4  First
4  1.0  3.0  2.0  2  Third
5  7.0  4.0  2.0  4  Forth

In [13]:
# natomiast do filtrowania brakujących danych istnieje już gotowa funkcja, którą
# łatwiej zapamiętać: "dropna()"

df.dropna()

     A    B    C  D      E
0  1.0  2.0  3.0  4  First
4  1.0  3.0  2.0  2  Third
5  7.0  4.0  2.0  4  Forth

In [14]:
# Funkcja dropna() nie usunie wierszy z bieżącej ramki danych, lecz
# tworzy nową ramkę danych bez brakujących wartości, dlatego
# trzeba wynik przypisać do nowej zmiennej:

new_df = df.dropna()

new_df

     A    B    C  D      E
0  1.0  2.0  3.0  4  First
4  1.0  3.0  2.0  2  Third
5  7.0  4.0  2.0  4  Forth

In [15]:
# Funkcja "dropna()" działa wg wierszy, aby usunąć kolumny z brakującymi wierszami
# podajemy parametr axis = 'columns' (lub axis = 1)

df.dropna(axis = 'columns')

   D
0  4
1  3
2  2
3  1
4  2
5  4

In [16]:
# Jak uzupełnić brakujące dane?
#
# W przypadku zmiennych skategoryzowanych:
# dodajemy nową klasę która reprezentuje brakujące wartości (np. "None", "Brak", etc)
# służy do tego funkcja "fillna()"

new_comlumn_e = df["E"].fillna("None")

new_comlumn_e

0    First
1     None
2     None
3    First
4    Third
5    Forth
Name: E, dtype: object

In [17]:
# podobnie możemy zamienić brakujące dane liczbowe
# gdy chcemy uzupelnic je jakąś stałą wartością domyślną
# W tym przykladzie uzupełnimy brakujące wartości w kolumnie A wartością 1


new_column = df["A"].fillna(1)

new_column

0    1.0
1    1.0
2    1.0
3    7.0
4    1.0
5    7.0
Name: A, dtype: float64

In [18]:
# możemy też wypenić braki poprzednimi wartościami
# użyjemy też funkcji fillna, ale z parametrem: method='ffill' (forward fill)

# df.fillna(method='ffill')
df.ffill()

     A    B    C  D      E
0  1.0  2.0  3.0  4  First
1  1.0  5.0  6.0  3  First
2  1.0  5.0  6.0  2  First
3  7.0  3.0  6.0  1  First
4  1.0  3.0  2.0  2  Third
5  7.0  4.0  2.0  4  Forth

In [19]:
# Inną metodą uzupełniania brakujących wartości liczbowych jest interpolacja wartości.
# W tym wypadku wartość zostanie obliczona jako średnia z wartośc przed i po w danej kolumnie.
# Jeśli będzie kilka brakujących wartości "pod rząd" to wartości zostaną uzupełnione
# tak, aby były w równych odstepach.

df.interpolate(method ='linear', limit_direction ='forward')

/tmp/ipykernel_256/1642922726.py:6: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method ='linear', limit_direction ='forward')

     A    B         C  D      E
0  1.0  2.0  3.000000  4  First
1  1.0  5.0  6.000000  3    NaN
2  1.0  4.0  4.666667  2    NaN
3  7.0  3.0  3.333333  1  First
4  1.0  3.0  2.000000  2  Third
5  7.0  4.0  2.000000  4  Forth

In [20]:
# Dodatkowe informacje o uzupełnianiu brakujących danych: https://pandas.pydata.org/docs/user_guide/missing_data.html

In [21]:
# Jak zamienić zmienne skategoryzowane na liczbowe?

In [22]:
# wczytujemy przykładowy zbiór danych zawierający kolumnę z wartościami
# skategoryzowanymi

categoric = pd.read_csv('https://raw.githubusercontent.com/mateuszr/ml-course-1/main/datasets/dummy-2.csv')

In [23]:
categoric

   Id         Item   Price
0   1          New  Medium
1   2  Second-hand  Medium
2   3          New  Medium
3   4          New    High
4   5  Second-hand     Low
5   6  Second-hand     Low
6   7          New  Medium

In [24]:
# Aby stworzyć tzw. sztuczne zmienne ("dummy variables") i zakodować
# wartości skategoryzowane jako "1 z n" możemy użyć funkcji "get_dummies()"
# w nastepujący sposób, podając nazwę kolumny którą chcemy zamienić na "1 z n":

pd.get_dummies(categoric.Item)

     New  Second-hand
0   True        False
1  False         True
2   True        False
3   True        False
4  False         True
5  False         True
6   True        False

In [25]:
# funkcja ta tylko zwróci nam nową reprezentację, ale stara ramka danych będzie bez zmian.
# musimy zatem skleić nową reprezentację ze starą ramką danych a następnie usunąć
# kolumnę którż już przekonwertowaliśmy ("Item"). przy pomocy funkcji "drop()"

new_columns = pd.get_dummies(categoric.Item)
new_df = pd.concat([categoric, new_columns], axis='columns')
new_df = new_df.drop(['Item'], axis='columns')

In [26]:
new_df

   Id   Price    New  Second-hand
0   1  Medium   True        False
1   2  Medium  False         True
2   3  Medium   True        False
3   4    High   True        False
4   5     Low  False         True
5   6     Low  False         True
6   7  Medium   True        False

In [27]:
# Możemy też reprezentować wartości skategoryzowane uporządkowane jako liczby
# Wtedy najłatwiej użyć funkcji "replace()" aby po prostu zamienić wartości
# z tekstowych w liczbowe.
# Funkcja "replace()" może zamienić wartości "w miejscu", tj. zaktualizuje
# nam bieżącą ramkę danych z nowymi wartościami.

df_replaced_values = new_df['Price'].replace(['Low', 'Medium', 'High'], [0, 1, 2])

df_replaced_values

/tmp/ipykernel_256/258485709.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_replaced_values = new_df['Price'].replace(['Low', 'Medium', 'High'], [0, 1, 2])

0    1
1    1
2    1
3    2
4    0
5    0
6    1
Name: Price, dtype: int64

In [28]:
new_df

   Id   Price    New  Second-hand
0   1  Medium   True        False
1   2  Medium  False         True
2   3  Medium   True        False
3   4    High   True        False
4   5     Low  False         True
5   6     Low  False         True
6   7  Medium   True        False

In [29]:
# innym sposobem na reprezentacje wartości skategoryzowanych jest użycie CategoricalDtype

from pandas.api.types import CategoricalDtype

# Define the ordered categories
price_categories = CategoricalDtype(['Low', 'Medium', 'High'], ordered=True)

# Convert the 'Price' column to an ordered categorical type
df_categorized_price = new_df['Price'].astype(price_categories)

df_categorized_price

0    Medium
1    Medium
2    Medium
3      High
4       Low
5       Low
6    Medium
Name: Price, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

This creates a Series with a `CategoricalDtype` where the order is explicitly defined. If you need numerical representation, you can then access the `codes` attribute of this categorical Series.

In [30]:
# To get the numerical representation (0, 1, 2, ...), you can access the .codes attribute
df_categorized_price_codes = df_categorized_price.cat.codes
display(df_categorized_price_codes)
print(f"Data type: {df_categorized_price_codes.dtype}")

0    1
1    1
2    1
3    2
4    0
5    0
6    1
dtype: int8

Data type: int8